version: "3.9"
services:
  spring-biblioteca-api:
    container_name: contenedor-bapi
    build: .
    ports:
      - "8080:8080"
    networks:
      - biblioteca-network
    depends_on:
      - mysql_biblioteca_database

  mysql_biblioteca_database:
    container_name: mysql_biblioteca_database
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliotecalpii
      MYSQL_USER: daniel
      MYSQL_PASSWORD: admin
    networks:
      - biblioteca-network
    volumes:
      - mysql-biblioteca-volume:/var/lib/mysql


networks:
  biblioteca-network:

volumes:
  mysql-biblioteca-volume: